apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: restore-sql-backup
  namespace: persistent-outreach
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      volumes:
      - name: gcp-serviceaccount
        secret:
          secretName: nebula-sql-backup-gcp
      containers:
      - image: ghcr.io/persistentss13/job-restore-sql-backup:latest
        name: restore-sql-backup
        volumeMounts:
        - name: gcp-serviceaccount
          mountPath: "/etc/gcp-sa"
        env:
        - name: BACKUP_FILE_NAME
          value: BOT_REPLACE_BACKUP_FILE_NAME
        envFrom:
        - secretRef:
            name: sql-creds
        - secretRef:
            name: nebula-sql-backup-gcs
        resources: {}
      restartPolicy: Never
status: {}